# Generated by Django 3.2.10 on 2021-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
