# Generated by Django 3.1 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210828_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('username', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('password', models.CharField(default='00000000', max_length=70)),
                ('name', models.CharField(default='abc', max_length=10)),
            ],
        ),
    ]
