# Generated by Django 4.0 on 2021-12-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
