# Generated by Django 3.2.10 on 2021-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart_signin_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='signincheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.BooleanField(default=False)),
            ],
        ),
    ]
