# Generated by Django 3.2.10 on 2021-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_signincheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='signincheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign', models.BooleanField(default=False)),
            ],
        ),
    ]
