# Generated by Django 3.2.10 on 2021-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_signincheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signincheck',
        ),
    ]
