# Generated by Django 4.0 on 2021-12-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_signincheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
